export * from './Home/Home'
export * from './AboutUs/AboutUs'
export * from './Statistics/Statistics'
export * from './Service/ServicePage'
export * from './Documentos/DocumentosPage'
export * from './Noticias/NoticiasPage'